### ISSUE TITLE
Clear input fields

### ISSUE THREAD

**Issue by idiliev18** [IPBachvarov18/CryptoZargan#16]
### Description
When the form is submitted, the fields must be cleared

### Due Date
2020-12-20

<img src = "https://cdn.discordapp.com/attachments/775422843990048818/776137118040457236/crypto_zargan.png" alt = "Crypto Zargan Logo">

**Comment by IDIliev18** [comment]
![download](https://user-images.githubusercontent.com/50216485/102723897-2f7c1500-4314-11eb-9276-98414d5990b8.jpg)
